// <auto-generated />
using MarcaPonto.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarcaPonto.DataBase.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20221022203423_MarcaPontoMigration")]
    partial class MarcaPontoMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("MarcaPonto.Model.Usuários.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = "6aaa5bc9-135d-4ebb-9cd5-366bd4480c66",
                            CPF = "1234567890",
                            Email = "Customer1@email.com",
                            Name = "Customer 01",
                            Password = "customer01",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = "811097d6-06b3-4e86-a7f5-019972384ac1",
                            CPF = "2234567890",
                            Email = "Customer2@email.com",
                            Name = "Customer 02",
                            Password = "customer02",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = "aa25f3c1-fbab-49ee-8138-8c8c4d99fa57",
                            CPF = "3234567890",
                            Email = "Customer3@email.com",
                            Name = "Customer 03",
                            Password = "customer03",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = "c798f23f-8b32-4382-8cf0-558f0cd9aa93",
                            CPF = "4234567890",
                            Email = "Customer4@email.com",
                            Name = "Customer 04",
                            Password = "customer04",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = "c4b77872-0989-4580-9aea-67247db10031",
                            CPF = "5234567890",
                            Email = "Customer5@email.com",
                            Name = "Customer 05",
                            Password = "customer05",
                            Role = "Customer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
